# Generated by Django 5.1 on 2024-10-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_user_profile_image_alter_user_profile_major2'),
    ]

    operations = [
        migrations.CreateModel(
            name='campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('points', models.IntegerField()),
                ('validation', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
