# Generated by Django 5.1 on 2024-10-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
                ('how_to_use', models.CharField(max_length=100)),
                ('why_to_use', models.CharField(max_length=100)),
                ('points_per_use', models.IntegerField()),
            ],
        ),
    ]
