# Generated by Django 5.1 on 2024-11-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
