# Generated by Django 5.1 on 2024-11-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_place_campaign_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
