# Generated by Django 5.1 on 2024-11-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_user_profile_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='rewards',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='reward_images/')),
                ('desc', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
