# Generated by Django 5.1 on 2024-11-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_rewards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rewards',
            new_name='reward',
        ),
    ]
