# Generated by Django 5.1 on 2024-12-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='places',
            field=models.ManyToManyField(to='pages.place'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
