# Generated by Django 5.1 on 2024-12-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_reward_places_alter_reward_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
