# Generated by Django 5.1 on 2024-12-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_reward_end_date_reward_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='new_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
