# Generated by Django 5.1 on 2024-12-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_transaction_new_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
